### ISSUE TITLE
Add black/white as default to ch-best-color-contrast()

### ISSUE THREAD

**Issue by voxpelli** [voxpelli/sass-color-helpers#4]
Got a request to add black/white as the default to `ch-best-color-contrast()` as in many cases those are the two colors that one are picking between, so not really necessary for people to specify them over and over again.

This way one would simply do: `color: ch-color-contrast($backgroundColor);` and it would return black if black has enough contrast against the background and otherwise white.

Ping @frebro

**Comment by frebro** [comment]
:+1: thanks!
